title: CV | Joey Anuff
description: from the Jekyll template by stavrospanakakis
url: https://januff.github.io/jekyll-cv/
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
